In [1]:
import pandas as pd

In [2]:
pakistan = pd.read_excel("../data/processed/pakistan.xlsx")

In [3]:
pakistan["provstate"].value_counts(dropna=False)

provstate
Balochistan                            4086
Khyber Pakhtunkhwa                     3621
Sindh                                  3305
Federally Administered Tribal Areas    2425
Punjab                                  890
North-West Frontier Province            866
Islamabad Capital Territory             164
Gilgit-Baltistan                         65
Unknown                                  51
Azad Kashmir                             31
Name: count, dtype: int64

In [4]:
sindh = pakistan[pakistan["provstate"] == "Sindh"].copy()

In [5]:
sindh.shape

(3305, 135)

In [6]:
sindh.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197011010001,1970,11,1,NaN,0,NaT,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
1,197402020001,1974,2,2,NaN,1,1974-02-03,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
6,197609300002,1976,9,30,NaN,0,NaT,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,1,1,1,1,NaN
8,197808020008,1978,8,2,NaN,0,NaT,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,1,1,1,1,NaN
18,198102160001,1981,2,16,NaN,0,NaT,153,Pakistan,6,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [7]:
sindh.info()

<class 'pandas.DataFrame'>
Index: 3305 entries, 0 to 15502
Columns: 135 entries, eventid to related
dtypes: datetime64[us](1), float64(50), int64(27), object(1), str(56)
memory usage: 3.4+ MB

In [8]:
sindh.isna()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,False,False,False,False,True,False,True,False,False,False,...,True,True,True,True,False,False,False,False,False,True
1,False,False,False,False,True,False,False,False,False,False,...,True,True,True,True,False,False,False,False,False,True
6,False,False,False,False,True,False,True,False,False,False,...,True,True,True,True,False,False,False,False,False,True
8,False,False,False,False,True,False,True,False,False,False,...,True,True,True,True,False,False,False,False,False,True
18,False,False,False,False,True,False,True,False,False,False,...,True,True,True,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15451,False,False,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
15488,False,False,False,False,True,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,False
15489,False,False,False,False,True,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,False
15495,False,False,False,False,True,False,True,False,False,False,...,True,False,False,False,False,False,False,False,False,True
15502,False,False,False,False,True,False,True,False,False,False,...,True,False,True,True,False,False,False,False,False,True

In [9]:
sindh.isna().sum()

eventid          0
iyear            0
imonth           0
iday             0
approxdate    3245
              ...
INT_LOG          0
INT_IDEO         0
INT_MISC         0
INT_ANY          0
related       2877
Length: 135, dtype: int64

In [13]:
sindh.isna().sum().sort_values(ascending=False)

gsubname3          3305
ransomnote         3305
weapsubtype4       3304
attacktype3        3304
attacktype3_txt    3304
                   ...
dbsource              0
INT_LOG               0
INT_IDEO              0
INT_MISC              0
INT_ANY               0
Length: 135, dtype: int64

In [19]:
null_sum = sindh.isna().sum()
null_sum[null_sum != 0]

approxdate    3245
resolution    3259
city             4
location      1771
summary       1218
              ...
addnotes      2830
scite1        1218
scite2        1851
scite3        2411
related       2877
Length: 98, dtype: int64

In [20]:
null_count = sindh.isna().sum()
null_percent = sindh.isna().mean() * 100

missing = pd.DataFrame({
    "null_count": null_count,
    "null_percent": null_percent
})

missing = missing[missing["null_count"] > 0].sort_values(
    "null_count",
    ascending=False
)

missing

               null_count  null_percent
ransomnote           3305    100.000000
gsubname3            3305    100.000000
weaptype4_txt        3304     99.969743
weaptype4            3304     99.969743
weapsubtype4         3304     99.969743
...                   ...           ...
natlty1                42      1.270802
natlty1_txt            42      1.270802
nkill                  36      1.089259
target1                 7      0.211800
city                    4      0.121029

[98 rows x 2 columns]

In [23]:
sindh.to_csv("../data/processed/sindh.csv")